AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: "ELB Kong"
Resources:
    EC2KongAlbSecurityGroup:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "ELB Kong"
            GroupName: "ELB Kong"
            VpcId: "vpc-0eed6c6b"
            SecurityGroupIngress: 
              - 
                CidrIp: "0.0.0.0/24"
                FromPort: 22
                IpProtocol: "tcp"
                ToPort: 22
              - 
                CidrIp: "0.0.0.0/0"
                FromPort: 80
                IpProtocol: "tcp"
                ToPort: 80
              - 
                CidrIp: "0.0.0.0/0"
                FromPort: 443
                IpProtocol: "tcp"
                ToPort: 443
            SecurityGroupEgress: 
              - 
                CidrIp: "0.0.0.0/0"
                IpProtocol: "-1"
Outputs:
  EC2KongAlbSecurityGroup:
    Description: Kong ECS SG
    Value: !Ref EC2KongAlbSecurityGroup
    Export:
      Name: EC2KongAlbSecurityGroup

