AWSTemplateFormatVersion: '2010-09-09'
Description: "Manages Kong-related Databases"

Parameters:
  SelectedVPC:
    Description: "The VPC in which to install Kong"
    Type: "AWS::EC2::VPC::Id"
    Default: "vpc-13123213"
  KongDatabaseName: # TODO: Provide Validations
    Type: "String"
    Default: "kong"
  KongaDatabaseName: # TODO: Provide Validations
    Type: "String"
    Default: "konga"
  DatabaseUser: # TODO: Provide Validations
    Type: "String"
    Default: "kong"
  DatabasePassword:
    Type: "String"
    NoEcho: true
    MinLength: "8"
    MaxLength: "16"
    ConstraintDescription: "Must be a String between 16 and 32 characters long."
    Default: "12345678"
  DatabaseSnapshotName:
    Type: "String"
    Default: ""

Conditions:
  UseDatabaseSnapshot: !Not [ !Equals [ !Ref DatabaseSnapshotName, "" ] ]


Resources:

  ###########################################################
  #                                                         #
  #   SECURITY GROUPS                                       #
  #                                                         #
  ###########################################################

  KongDevDatabaseSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: "Kong DEV RDS"
      GroupDescription: !Sub "Security Group for Kong RDS (${SelectedVPC})"
      VpcId: !Ref SelectedVPC

  KongDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
        DBSubnetGroupDescription: kong-dev
        DBSubnetGroupName: kong-dev
        SubnetIds:
            - subnet-324234234
            - subnet-324234234
            - subnet-ewrewrewe
            - subnet-werwerere
  
  ###########################################################
  #                                                         #
  #   RDS DATABASES                                         #
  #                                                         #
  ###########################################################

  KongDatabase:
    Type: "AWS::RDS::DBInstance"
    DeletionPolicy: "Snapshot"
    Properties:
      AllocatedStorage: "20"
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: "2"
      DBInstanceClass: "db.t2.micro"
      DBName:
        Fn::If:
        - UseDatabaseSnapshot
        - !Ref AWS::NoValue
        - !Ref KongDatabaseName
      DBInstanceIdentifier: "kong-dev"
      DBSnapshotIdentifier:
        Fn::If:
        - UseDatabaseSnapshot
        - !Ref DatabaseSnapshotName
        - !Ref AWS::NoValue
      Engine: "postgres"
      EngineVersion: "9.6.6"
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
      PubliclyAccessible: true
      # For Read replicas in the future! See docs for more info
      # SourceDBInstanceIdentifier: String
      DBSubnetGroupName: !Ref KongDBSubnetGroup
      VPCSecurityGroups:
        - !ImportValue EC2KongDatabaseSecurityGroup
        - !Ref KongDevDatabaseSecurityGroup
  DNSRecordSet:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneName: kong.com.
        Name: kong-database.kong.com
        Type: CNAME
        TTL: '30'
        ResourceRecords:
        - {"Fn::GetAtt": ["KongDatabase","Endpoint.Address"]}
      DependsOn: KongDatabase

Outputs:
  KongDevDatabaseSecurityGroup:
    Description: SG to be assigned to the Kong RDS cluster
    Value: !Ref KongDevDatabaseSecurityGroup
    Export:
      Name: KongDevDatabaseSecurityGroup
  KongDatabase:
    Description: The Kong Database
    Value: !Ref KongDatabase
    Export:
      Name: KongDatabase
  KongDatabaseDNSAddress:
    Description: The DNS address of the Kong Database
    Value: kong-database.development.rentcars.com
    Export:
      Name: KongDatabaseDNSAddress
