AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: "ECS Kong"
Resources:
    EC2KongEcsSecurityGroup:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "ECS Kong"
            GroupName: "ECS Kong"
            Tags: 
              - 
                Key: "Name"
                Value: "EC2 Kong"
            VpcId: "vpc-13123343"
            SecurityGroupIngress: 
              - 
                CidrIp: "0.0.0.0/24"
                FromPort: 22
                IpProtocol: "tcp"
                ToPort: 22
              - 
                CidrIp: "0.0.0.0/0"
                FromPort: 80
                IpProtocol: "tcp"
                ToPort: 80
              - 
                CidrIp: "0.0.0.0/0"
                FromPort: 443
                IpProtocol: "tcp"
                ToPort: 443
            SecurityGroupEgress: 
              - 
                CidrIp: "0.0.0.0/0"
                IpProtocol: "-1"
Outputs:
  EC2KongEcsSecurityGroup:
    Description: Kong ECS SG
    Value: !Ref EC2KongEcsSecurityGroup
    Export:
      Name: EC2KongEcsSecurityGroup
